### ISSUE TITLE
Reading feature failed

### ISSUE THREAD

**Issue by GaofengCheng** [vrenkens/tfkaldi#4]
Hi Vrenkens, I'm very interesting in your project. I'm now trying your project, but encountered some problems. 
I'm running my experiments on WSJ. And the feature is made by kaldi (compress false), I begin from  `TRAIN_NNET` .
I changed the `config_AURORA4.cfg`as follow:
```
train_features=/nobackup/datapool/project/proa/usr/wsj/s5/data
expdir = /nobackup/datapool/project/proa/chenggaofeng/wsj/s5/exp
num_jobs = 20
name = tfkaldi_train_si284_hires (gmm,dnn, rename train_si284_hires as tfkaldi_train_si284_hires)
gmm_name = tri4b_tfkaldi (rename the tri4b as tri4b_tfkaldi)

```
while keeping all the rest as default.
But when I run `main.py`, it shows( I have adding some auxiliary code to show necessary information):
```
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
num_labels: 3399
input_dim: 40
------- shuffling examples ----------
train_data_root: /nobackup/datapool/project/proa/chenggaofeng/wsj/s5/data/tfkaldi_train_si284_hires
------- training neural net ----------
featdir: /nobackup/datapool/project/proa/chenggaofeng/wsj/s5/data/tfkaldi_train_si284_hires
Traceback (most recent call last):
  File "main.py", line 156, in <module>
    Nnet.train(config.get('directories','train_features') + '/' +  config.get('dnn-features','name'), alifile)
  File "neuralNetworks/nnet.py", line 77, in train
    dispenser = batchdispenser.Batchdispenser(reader, int(self.conf['batch_size']), alifile, self.DNN.output_dim)
  File "io/batchdispenser.py", line 77, in __init__
    self.alignments = kaldiInterface.read_alignments(alifile)
  File "kaldi/kaldiInterface.py", line 20, in read_alignments
    alignments[data[0]] = np.asarray(map(int,data[1:len(data)])) #segment:alignment
ValueError: invalid literal for int() with base 10: ''
```

Hope to get your help .

**Comment by vrenkens** [comment]
Hi Gaofeng,

Something was going wrong when reading your alignments (space was 
inserted), it should work now with the most recent commit. Could you 
test it and confirm?
